#### This file is to create S3 bucket where data files are uploaded and stored.
####  Later, the data in the file will be loaded through ETL process to Database


locals {
  datafolder_onpremise="${path.module}/data"
}

# to create S3 bucket for uploaded data file
#==================================================x==========
#1 to create s3 bucket to store data files
    #1.1 to create s3 bucket 
    #1.2 to create s3 bucket policy
    # the policy can be generated by Cloudfront AWS
    # or created manually by us
    #1.3 to attach the policy to s3
#2 to upload state files from locally to s3 (index.html, ....)
#3 to configure s3 to trigger SQS (in another file)
  # later sqs will trigger lambda
#4 to create GateWay VPC Endpoint for s3
  # lambda in the vpc with private subnet does not have internet connection 
  # Gateway VPC Endpoint allows traffic among resources in and out of VPC 
  # can go through Amazon Network. 

#============================================================
#1 below is to create s3 for storing files like index.html
resource "aws_s3_bucket" "data_analysis" {
  bucket = "${local.bucket_name_for_db}"
  force_destroy = true
  tags = {
    Name        = "${local.bucket_name_for_db}"
    Environment = "Dev"
  }
} 
resource "aws_s3_bucket_versioning" "s3_versioning" {
  bucket = aws_s3_bucket.data_analysis.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "private_s3" {
  bucket = aws_s3_bucket.data_analysis.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
#=======================================================
#2 below is to upload data files to the newly built s3 bucket

#resource "aws_s3_object" "upload_state_files" {
  #for_each = fileset("./${local.datafolder_onpremise}/", "**/*")
  #bucket = aws_s3_bucket.data_analysis.id
  #key = each.value
  #source = "./${local.datafolder_onpremise}/${each.value}"
#}

#=====================================================================
# 4 in file of 'loading lambda'
